// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezgjpgzcdwcifdmwploc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6Z2pwZ3pjZHdjaWZkbXdwbG9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5OTI2NzAsImV4cCI6MjA4NDU2ODY3MH0.efhz-XGWZgob46sLqQKzsdk3N2sKSotdT_0C6DTr_nM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});